spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: <host1:port1>,<host1:port1>
      bindings:
        stockdata-in:
          destination: stockdata
          contentType: application/json
        stockdata-out:
          destination: stockdata
          contentType: application/json
  data: 
    mongodb: 
      uri: mongodb://<host1:port1>/stock

logging:
  level:
    org.springframework.web: ERROR
    com.sapient.retail.service.streamkafka: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

custom:
  demandInfoProvider: "demandInfoProvider"
  supplyInfoProvider: "supplyInfoProvider"