language: java

sudo: required

services:
  - docker

jdk:
  - openjdk8

install: ./gradlew clean assemble
script:
  #- ./gradlew test jacocoTestReport
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
    docker build -t "$DOCKER_REPO:$TRAVIS_COMMIT" -f stock-exposer/DockerFileTravis . ;
    fi
  #- export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
  #- echo $TAG
  #- export REPO="raghavarora12/retailreactive"
  #- docker build -t "raghavarora12/retailreactive:latest" -f stock-exposer/DockerFileTravis .

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker ps -a
  - docker images
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
    docker images
    docker push "$DOCKER_REPO:$TRAVIS_COMMIT"
    docker images
    docker tag $DOCKER_REPO:$TRAVIS_COMMIT $DOCKER_REPO:"latest";
    docker images
    docker push $DOCKER_REPO:"latest";
    docker images
    fi
  - docker images
#  - docker push "raghavarora12/retailreactive":"latest"
#  - docker push "$REPO:$TAG"
