language: java

sudo: required

services:
  - docker

jdk:
  - openjdk8

install: ./gradlew clean assemble
script:
  - ./gradlew test jacocoTestReport
  - export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
  - export REPO_I="raghavarora12"
  - export REPO_N="retailreactive"
  - export REPO=$REPO_I/$REPO_N
  - docker build -t "raghavarora12/retailreactive:latest" -f stock-exposer/DockerFileTravis .

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker ps -a
  - docker images
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
    docker tag $REPO:$TAG $REPO:$TRAVIS_BUILD_NUMBER;
    docker push $REPO:$TRAVIS_BUILD_NUMBER;
    fi
  - docker push "raghavarora12/retailreactive":"latest"
  - docker push $REPO:$TAG
