spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        stockdata-in:
          destination: stockdata
          contentType: application/json
        stockdata-out:
          destination: stockdata
          contentType: application/json
