spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: del2vmplcireative01.sapient.com:32782,del2vmplcireative01.sapient.com:32783
      bindings:
        stockdata-in:
          destination: stockdata
          contentType: application/json
        stockdata-out:
          destination: stockdata
          contentType: application/json
  data: 
    mongodb: 
      uri: mongodb://del2vmplcireative03.sapient.com:27017/stock