spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: <host1:port1,host2:port2>
      bindings:
        stockdata-in:
          destination: stockdata
          contentType: application/json
        stockdata-out:
          destination: stockdata
          contentType: application/json
  data: 
    mongodb: 
      uri: mongodb://<host1>:<port1>/stock