spring:
  data: 
    mongodb: 
      uri: mongodb://localhost:27017/stock
logging:
  level:
    org.springframework.web: ERROR
    com.sapient.retail.service.streamkafka: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
