version: '3.3'

services:
  reactiveretail-stock-exposer:
    image: reactiveretail/stock-exposer
    build: .
    ports:
      - 8181:8080
    deploy:
      replicas: 2
    environment:
      KAFKA_HOST: $KAFKA_HOST
      DB_HOST: $DB_HOST
