
resources:
  - name: source
    type: git
    source:
      uri: https://github.com/SapInnovation/reactiveretail-stock.git
      branch: master
  - name: docker-hub
    type: docker-image
    source:
      email: rsingh24@sapient.com
      username: reactiveretail
      password: passw0rd
      repository: reactiveretail/stock-exposer

jobs:
  - name: build-image
    public: true
    plan:
    - get: source
      trigger: true
    - put: docker-hub
      params:
        build: source/stock-exposer

  - name: deploy-image
    public: true
    plan:
    - get: source
      trigger: true
      passed: [build-image]
    - task: deploy
      config:
        inputs:
        - name: source
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: frolvlad/alpine-bash
        run:
          path: ./source/ci/deploy.sh
        params:
            USER_NAME: root
            USER_PASS: sapient@123
              HOST_NAME: del2vmplcireative05.sapient.com
            SERVICE: exposer
