
resources:
  - name: source
    type: git
    source:
      uri: https://github.com/SapInnovation/reactiveretail-stock.git
      branch: quickBuildDeployTravis
      path:
        - ci/**
        - stock-common/**
        - stock-stream-processor/**
  - name: docker-hub
    type: docker-image
    source:
      email: ((auth-data.DOCKER_REPO_EMAIL))
      username: ((auth-data.DOCKER_REPO_USER))
      password: ((auth-data.DOCKER_REPO_PWD))
      repository: reactiveretail/stock-stream-processor

jobs:
  - name: deploy-image
    public: true
    plan:
    - get: docker-hub
      trigger: true
    - task: deploy
      config:
        inputs:
        - name: source
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: reactiveretail/stock-exposer
        run:
          path: ./source/ci/deploy.sh
        params:
            USER_NAME: ((auth-data.DESTINATION_SERVER_USER))
            USER_PASS: ((auth-data.DESTINATION_SERVER_PWD))
            HOST_NAME: ((auth-data.DESTINATION_SERVER_HOST))
            SERVICE: processor
            KAFKA_HOST: ((auth-data.KAFKA_HOST))
            DB_HOST: ((auth-data.DB_HOST))
