
resources:
  - name: git-source
    type: git
    source:
      uri: https://github.com/SapInnovation/reactiveretail-stock.git
      branch: master
      path:
        - ci/**
        - stock-common/**
        - stock-exposer/**
  - name: docker-hub
    type: docker-image
    source:
      email: ((auth-data.DOCKER_REPO_EMAIL))
      username: ((auth-data.DOCKER_REPO_USER))
      password: ((auth-data.DOCKER_REPO_PWD))
      repository: reactiveretail/stock-exposer

jobs:
  - name: build-image
    public: true
    plan:
    - get: git-source
      trigger: true
    - put: docker-hub
      params:
        build: git-source/stock-exposer
        tag: git-source/.git/HEAD
        tag_as_latest: true

  - name: deploy-image
    public: true
    plan:
    - get: git-source
      trigger: true
      passed: [build-image]
    - task: deploy
      config:
        inputs:
        - name: git-source
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: frolvlad/alpine-bash
        run:
          path: ./git-source/ci/deploy.sh
        params:
            USER_NAME: ((auth-data.DESTINATION_SERVER_USER))
            USER_PASS: ((auth-data.DESTINATION_SERVER_PWD))
            HOST_NAME: ((auth-data.DESTINATION_SERVER_HOST))
            SERVICE: exposer
            DB_HOST: ((auth-data.DB_HOST))
