groups: []
resources:
- name: source
  type: git
  source:
    branch: quickBuildDeployTravis
    path:
    - ci/**
    - stock-common/**
    - stock-exposer/**
    uri: https://github.com/SapInnovation/reactiveretail-stock.git
- name: docker-hub
  type: docker-image
  source:
    email: ((auth-data.DOCKER_REPO_EMAIL))
    username: ((auth-data.DOCKER_REPO_USER))
    password: ((auth-data.DOCKER_REPO_PWD))
    repository: reactiveretail/stock-exposer
resource_types: []
jobs:
- name: deploy-image
  public: true
  plan:
  - get: docker-hub
    trigger: true
  - get: source
  - task: deploy
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          email: ((auth-data.DOCKER_REPO_EMAIL))
          username: ((auth-data.DOCKER_REPO_USER))
          password: ((auth-data.DOCKER_REPO_PWD))
          repository: reactiveretail/stock-exposer
      params:
        USER_NAME: ((auth-data.DESTINATION_SERVER_USER))
        USER_PASS: ((auth-data.DESTINATION_SERVER_PWD))
        HOST_NAME: ((auth-data.DESTINATION_SERVER_HOST))
        SERVICE: exposer
        DB_HOST: ((auth-data.DB_HOST))
      run:
        path: source/ci/deploy.sh
      inputs:
      - name: source
