
resources:
  - name: source
    type: git
    source:
      uri: https://github.com/SapInnovation/reactiveretail-stock.git
      branch: master
  - name: docker-hub
    type: docker-image
    source:
      email: ((authdata.DOCKER_HUB_EMAIL))
      username:((authdata.DOCKER_HUB_USER))
      password: ((authdata.DOCKER_HUB_PWD))
      repository: reactiveretail/stockservice

jobs:
  - name: build-image
    public: true
    plan:
    - get: source
      trigger: true
    - put: docker-hub
      params:
        build: source/docker

  - name: deploy-image
    public: true
    plan:
    - get: source
      trigger: true
      passed: [build-image]
    - task: deploy
      config:
        inputs:
        - name: source
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: frolvlad/alpine-bash
        run:
          path: ./source/ci/deploy.sh
        params:
            USER_NAME: ((authdata.REMOTE_SERVER_USER))
            USER_PASS: ((authdata.REMOTE_SERVER_PWD))
            HOST_NAME: ((authdata.REMOTE_SERVER_HOST))
